"""Transform activity logging

Revision ID: 14bcc347e55c
Revises: 1b8417b89153
Create Date: 2023-08-01 10:20:50.409263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "14bcc347e55c"
down_revision = "1b8417b89153"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transformactivity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("rows", sa.Integer(), nullable=False),
        sa.Column("data_import", sa.Boolean(), nullable=False),
        sa.Column("researcher_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["researcher_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transformactivity_id"), "transformactivity", ["id"], unique=False)
    op.add_column("product", sa.Column("rows", sa.Integer(), server_default=sa.text("0"), nullable=False))
    op.add_column("product", sa.Column("transforms", sa.Integer(), server_default=sa.text("0"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "transforms")
    op.drop_column("product", "rows")
    op.drop_index(op.f("ix_transformactivity_id"), table_name="transformactivity")
    op.drop_table("transformactivity")
    # ### end Alembic commands ###
