"""Features and sources

Revision ID: 3eda5c2955b5
Revises: 14bcc347e55c
Create Date: 2024-01-13 15:14:15.104566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3eda5c2955b5"
down_revision = "14bcc347e55c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reference", sa.Column("isFeatured", sa.Boolean(), server_default=sa.sql.false(), nullable=False))
    op.add_column("resource", sa.Column("sourceURL", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "sourceURL")
    op.drop_column("reference", "isFeatured")
    # ### end Alembic commands ###
