[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "app"
dynamic = ["version"]
description = "Whyqd hub for visual schema crosswalks and transforms of tabular data."
readme = "README.md"
requires-python = ">=3.11"
license = "AGPL-3.0"
keywords = []
authors = [
  { name = "Gavin Chait", email = "gchait@whythawk.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "inboard[fastapi]==0.72.2",
  "python-multipart>=0.0.12,<1.0.0",
  "email-validator>=2.2.0",
  "requests>=2.28.1",
  "celery>=5.4.0",
  "passlib[bcrypt]>=1.7.4",
  "tenacity>=8.2.0",
  "emails>=0.6.0",
  "raven>=6.10.0",
  "jinja2>=3.1.2",
  "alembic>=1.13.3",
  "sqlalchemy>=2.0.36",
  "python-jose[cryptography]>=3.3.0",
  "httpx>=0.23.1",
  "psycopg[binary]>=3.2.3",
  "setuptools>=67.7.2",
  "sqlalchemy-utils>=0.41.1",
  "argon2-cffi>=23.1.0",
  "websockets>=12.0",
  "whyqd>=1.2.4",
  "stripe>=5.4.0",
  "ip2location>=8.10.0",
  "orjson>=3.9.5",
  "boto3>=1.35.43",
  "Babel>=2.12.1"
]

[project.optional-dependencies]
checks = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "isort>=5.11.2",
  "autoflake>=2.0.0",
  "flake8>=6.0.0",
]

[project.urls]
Documentation = "https://github.com/whythawk/whyqd-hub/tree/main/docs"
Issues = "https://github.com/whythawk/whyqd-hub/issues"
Source = "https://github.com/whythawk/whyqd-hub"

[tool.hatch.version]
path = "app/__version__.py"

[dirs.env]
virtual = "./.venv"

[tool.hatch.envs.default]
python="3.11"
dev-mode = true
dependencies = []

[tool.hatch.build.targets.sdist]
include = ["/app"]

[tool.hatch.envs.production]
dev-mode = false
features = []
path = ".venv"

[tool.hatch.envs.lint]
detached = true
dependencies = [
  "black>=23.1.0",
  "mypy>=1.0.0",
  "isort>=5.11.2",
]
[tool.hatch.envs.lint.scripts]
style = [
  "isort --check --diff {args:.}",
  "black --check --diff {args:.}",
]
fmt = [
  "black {args:.}",
  "isort {args:.}",
  "style",
]
all = [
  "style",
  "typing",
]

[tool.black]
target-version = ["py311"]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 120
src_paths = ["app", "tests"]

[tool.mypy]
files = ["**/*.py"]
plugins = "pydantic.mypy"
show_error_codes = true
strict = true